### ISSUE TITLE
Disable models from using replicas

### ISSUE THREAD

**Issue by erkie** [joinhandshake/knockoff#14]
Is it possible to disable a model from never using replicas without going through `Knockoff.on_primary` on each query, for example `User.find()`? 

Right now I'm wrapping an action with `around_action` to use replication only on `GET`-requests:

```ruby
  def force_master_database_on_post(&block)
    if request.method_symbol != :get
      DatabaseReplica.with_primary_replication(&block)
    else
      yield
    end
  end
```

But now looking into that I don't want replication on key models like the User model, or anything related to payments as examples.

**Comment by sgringwe** [comment]
@erkie currently there is no way to enforce that specifically for a model, and not currently on the roadmap.

my hunch is that there'd be some monkeypatching into active record that could accomplish this for your application.

this will only get you partway, but you can also use controller based logic to wrap your payments controller to use the primary.

**Comment by erkie** [comment]
Thanks for the answer. If it's not currently on the roadmap, I'll close the ticket and implement something in my code. :)
