### ISSUE TITLE
Thread safety of Knockoff connections in Sidekiq?

### ISSUE THREAD

**Issue by drn** [joinhandshake/knockoff#16]
Hi everyone,

We recently started using Knockoff to offload specific read-only workloads to a read replica. We're running into occasional exceptions when using Knockoff to connect to a read replica within a Sidekiq job:

```
ActiveRecord::ConnectionNotEstablished: No connection pool with 'Knockoff::KnockoffReplica0' found.
  from active_record/connection_adapters/abstract/connection_pool.rb:930:in `retrieve_connection'
  from active_record/connection_handling.rb:116:in `retrieve_connection'
  from active_record/connection_handling.rb:88:in `connection'
  from knockoff/active_record/base.rb:11:in `connection'
  from active_record/associations/association.rb:97:in `association_scope'
  from active_record/associations/association.rb:86:in `scope'
  from active_record/associations/collection_association.rb:285:in `scope'
  from active_record/associations/collection_proxy.rb:961:in `scope'
  from active_record/associations/collection_proxy.rb:1133:in `scoping'
  from active_record/relation/delegation.rb:90:in `method_missing'
```

For the job that recently raised this error, we're at a Sidekiq concurrency of 3 and have specified a pool of 30 for the read replica's database url. 

Reading similar reports of [this error](https://github.com/mperham/sidekiq/issues/3988), the reports seem to point to thread safety issues in the database connection adapter.

Is there anything that we need to do before using the `Knockoff.on_replica { ... }` method in Sidekiq? I saw the [forking note](https://github.com/joinhandshake/knockoff#forking) in the README - do we need to call `Knockoff.disconnect_all!` somewhere in the Sidekiq boot process?

Any advice would be appreciated. I can submit a PR to update relevant docs if we get to the bottom of this

Thanks!

**Comment by sgringwe** [comment]
Hey @drn - unfortunately I don't have any additional information to help here other than what is in the README already. If you do discover a solution though, happy to review a PR
